version: '3'

tasks:
  mbp-14:
    desc: Switch nix-darwin on mbp-14
    cmds:
      - sudo darwin-rebuild switch --flake .#mbp-14

  z2-mini:
    desc: Switch nixos on z2-mini
    cmds:
      - sudo nixos-rebuild switch --flake .#z2-mini

  update:
    desc: Update nix flake
    cmds:
      - nix flake update

  ssh:
    desc: SSH into z2-mini
    cmds:
      - ssh z2-mini

  yubikey-generate:
    desc: Generate a new resident SSH key (usage; task yubikey-generate NAME=id_yubikey_1)
    vars:
      NAME: '{{.NAME | default "id_yubikey_1"}}'
    cmds:
      - ssh-keygen -t ed25519-sk -O resident -O application=ssh:wjkoh -N "" -f ~/.ssh/{{.NAME}}

  yubikey-recover:
    desc: Recover resident keys from YubiKey (usage; task yubikey-recover NAME=id_yubikey_1)
    vars:
      NAME: '{{.NAME | default "id_yubikey_recover"}}'
    cmds:
      - 'echo "NOTE: If you have multiple resident keys, ssh-keygen may create files with suffixes (e.g., id_ed25519_sk_rk_...). Check output if rename fails."'
      - mkdir -p ~/.ssh
      - cd /tmp && ssh-keygen -K
      - mv /tmp/id_ed25519_sk ~/.ssh/{{.NAME}}
      - mv /tmp/id_ed25519_sk.pub ~/.ssh/{{.NAME}}.pub
      - chmod 600 ~/.ssh/{{.NAME}}
      - echo "Key recovered to ~/.ssh/{{.NAME}}"
